services:

  db:
    image: mysql:8.0
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - db_data_outthink:/var/lib/mysql

  wordpress:
    build:
      context: .

    restart: unless-stopped

    depends_on:
      - db

    ports:
      - "8081:80"

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}

    volumes:
      - ./:/var/www/html
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  db_data_outthink: